#pragma once

#define NUM_SUBLAYERS 10
#define ANIMATION_BG_LAYER 1 * NUM_SUBLAYERS
#define ANIMATION_MG_LAYER 2 * NUM_SUBLAYERS
#define ANIMATION_FG_LAYER 3 * NUM_SUBLAYERS
#define BEATPATH_LAYER 4 * NUM_SUBLAYERS